name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Make sure this matches your actual branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Increment project version
      run: |
        mvn build-helper:parse-version
        mvn versions:set -DnewVersion="${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.INCREMENTAL_VERSION + 1 }}-SNAPSHOT" versions:commit
        git add pom.xml
        git commit -m "Increment version number"
        git push

    - name: Get Maven version
      run: |
        MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "MAVEN_VERSION=$MAVEN_VERSION" >> $GITHUB_ENV
        echo "New version: $MAVEN_VERSION"

    - name: Build Docker image
      run: docker build -t idan5567/github:${{ env.MAVEN_VERSION }} .

    - name: Log in to Docker registry
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push idan5567/github:${{ env.MAVEN_VERSION }}

