name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Make sure this matches your actual branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Configure Git
      run: |
        git config --global user.name ${{ secrets.HUB_USER }}
        git config --global user.email ${{ secrets.HUB_MAIL }}

    - name: Parse project version and increment
      run: |
        mvn build-helper:parse-version
        echo "MAJOR_VERSION=$(mvn help:evaluate -Dexpression=parsedVersion.majorVersion -q -DforceStdout)" >> $GITHUB_ENV
        echo "MINOR_VERSION=$(mvn help:evaluate -Dexpression=parsedVersion.minorVersion -q -DforceStdout)" >> $GITHUB_ENV
        echo "INCREMENTAL_VERSION=$(mvn help:evaluate -Dexpression=parsedVersion.nextIncrementalVersion -q -DforceStdout)" >> $GITHUB_ENV
        mvn versions:set -DnewVersion="${MAJOR_VERSION}.${MINOR_VERSION}.${INCREMENTAL_VERSION}-SNAPSHOT" versions:commit
        git add pom.xml

    - name: Commit and push version change
      run: |
        git diff-index --quiet HEAD || git commit -m "Increment version number to ${MAJOR_VERSION}.${MINOR_VERSION}.${INCREMENTAL_VERSION}-SNAPSHOT"
        git push


    - name: Print environment variables
      run: |
        echo "Major version: $MAJOR_VERSION"
        echo "Minor version: $MINOR_VERSION"
        echo "Incremental version: $INCREMENTAL_VERSION"

  
    - name: Build Docker image
      run: |
        docker build -t idan5567/github:${MAJOR_VERSION}.${MINOR_VERSION}.${INCREMENTAL_VERSION}-SNAPSHOT .

    - name: Log in to Docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: |
        docker push idan5567/github:${MAJOR_VERSION}.${MINOR_VERSION}.${INCREMENTAL_VERSION}-SNAPSHOT

    - name: Create and push git tag
      run: |
        git tag v${MAJOR_VERSION}.${MINOR_VERSION}.${INCREMENTAL_VERSION}-SNAPSHOT
        git push origin v${MAJOR_VERSION}.${MINOR_VERSION}.${INCREMENTAL_VERSION}-SNAPSHOT


