name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    # Extract version from Maven (pom.xml)
    - name: Get Maven version
      id: maven-version
      run: echo "MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    # Other steps like version bumping, etc.

    - name: Build Docker image
      run: docker build -t idan5567/github:$MAVEN_VERSION .

    - name: Log in to Docker registry
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push yourusername/hello:$MAVEN_VERSION
